name: BukkitSerializationInterface
main: com.github.kory33.bukkitserializationinterface.BukkitSerializationInterfacePlugin
version: 0.0.1-SNAPSHOT

commands:
    serialinterface:
        description: commands related to the interface of item serialization
        usage: /serialinterface (serialfromitem|(itemfromserial <PlayerId> <serial>))
        permission: serializationinterface.usecommand
        permission-message: You do not have /<permission> to execute this command.

permissions:
    serializationinterface.use:
        description: Allows a player to use the serialization/deserialization interface
        default: op
