name: BukkitSerializationInterface
main: com.github.kory33.bukkitserializationinterface.BukkitSerializationInterfacePlugin
version: 0.0.1

commands:
    serialinterface:
        description: commands related to the interface of item serialization
        usage: /serialinterface (serializeitem|(deserializeitem <PlayerId> <serial>))
        permission-message: You do not have /<permission> to execute this command.

permissions:
    serialinterface.usecommand:
        description: Allows a player to use the serialization/deserialization interface
        default: op
    serialinterface.serializeitem:
        description: Allows the player to get serialized data of an item
        default: op
    serialinterface.deserializeitem:
        description: Allows the player to get itemstack from serialized data
        default: op
